In [2]:
import pandas as pd
from pathlib import Path

# Define file paths
data_folder = Path(r"D:\Learnings\de_project\raw\customers_orderslist")

# Full paths to CSVs
customers_file = data_folder / "olist_customers_dataset.csv"
orders_file = data_folder / "olist_orders_dataset.csv"
order_items_file = data_folder / "olist_order_items_dataset.csv"
products_file = data_folder / "olist_products_dataset.csv"

# Read CSVs
df_customers = pd.read_csv(customers_file)
df_orders = pd.read_csv(orders_file)
df_order_items = pd.read_csv(order_items_file)
df_products = pd.read_csv(products_file)

In [3]:
print(df_customers.shape)
print(df_customers.columns)
print(df_customers.dtypes)
print(df_customers.head())

(99441, 5)
Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP

In [4]:
    # --- 3. Define inspection function ---
def inspect_df(df, name):
        print(f"\n--- {name} ---")
        print("Shape:", df.shape)
        print("Columns:", df.columns.tolist())
        print("cols:", df.columns.tolist())
        print("head:", df.head)
        print("Data types:\n", df.dtypes)
        print("Missing values:\n", df.isnull().sum())
        print("Duplicate rows:", df.duplicated().sum())

        # Identify categorical, numeric, date columns
        categorical_cols = df.select_dtypes(include='object').columns.tolist()
        numeric_cols = df.select_dtypes(include='number').columns.tolist()
        date_cols = [col for col in df.columns if 'date' in col or 'timestamp' in col]

        print("Categorical columns:", categorical_cols)
        print("Numeric columns:", numeric_cols)
        print("Date columns:", date_cols)
        print("-" * 50)

    # --- 4. Inspect all files ---
files = {
        "Customers": df_customers,
        "Orders": df_orders,
        "Order Items": df_order_items,
        "Products": df_products
}

for name, df in files.items():
        inspect_df(df, name)

--- Customers ---
Shape: (99441, 5)
Columns: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']
cols: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']
head: <bound method NDFrame.head of                             customer_id                customer_unique_id  \
0      06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1      18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2      4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3      b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4      4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066
...                                 ...                               ...
99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

       customer_zip_code_prefix          customer_city customer_state
0                         14409                 franca             SP
1                          9790  sao bernardo do campo             SP
2                          1151              sao paulo             SP
3                          8775        mogi das cruzes             SP
4                         13056               campinas             SP
...                         ...                    ...            ...
99436                      3937              sao paulo             SP
99437                      6764        taboao da serra             SP
99438                     60115              fortaleza             CE
99439                     92120                 canoas             RS
99440                      6703                  cotia             SP

[99441 rows x 5 columns]>
Data types:
 customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object
Missing values:
 customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
Duplicate rows: 0
Categorical columns: ['customer_id', 'customer_unique_id', 'customer_city', 'customer_state']
Numeric columns: ['customer_zip_code_prefix']
Date columns: []
--------------------------------------------------

--- Orders ---
Shape: (99441, 8)
Columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
cols: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
head: <bound method NDFrame.head of                                order_id                       customer_id  \
0      e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1      53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2      47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3      949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4      ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c
...                                 ...                               ...
99436  9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00
99437  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7
99438  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c
99439  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
99440  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24

      order_status order_purchase_timestamp    order_approved_at  \
0        delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1        delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2        delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3        delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4        delivered      2018-02-13 21:18:39  2018-02-13 22:20:29
...            ...                      ...                  ...
99436    delivered      2017-03-09 09:54:05  2017-03-09 09:54:05
99437    delivered      2018-02-06 12:58:58  2018-02-06 13:10:37
99438    delivered      2017-08-27 14:46:43  2017-08-27 15:04:16
99439    delivered      2018-01-08 21:28:27  2018-01-08 21:36:21
99440    delivered      2018-03-08 20:57:30  2018-03-09 11:20:28

      order_delivered_carrier_date order_delivered_customer_date  \
0              2017-10-04 19:55:00           2017-10-10 21:25:13
1              2018-07-26 14:31:00           2018-08-07 15:27:45
2              2018-08-08 13:50:00           2018-08-17 18:06:29
3              2017-11-22 13:39:59           2017-12-02 00:28:42
4              2018-02-14 19:46:34           2018-02-16 18:17:02
...                            ...                           ...
99436          2017-03-10 11:18:03           2017-03-17 15:08:01
99437          2018-02-07 23:22:42           2018-02-28 17:37:56
99438          2017-08-28 20:52:26           2017-09-21 11:24:17
99439          2018-01-12 15:35:03           2018-01-25 23:32:54
99440          2018-03-09 22:11:59           2018-03-16 13:08:30

      order_estimated_delivery_date
0               2017-10-18 00:00:00
1               2018-08-13 00:00:00
2               2018-09-04 00:00:00
3               2017-12-15 00:00:00
4               2018-02-26 00:00:00
...                             ...
99436           2017-03-28 00:00:00
99437           2018-03-02 00:00:00
99438           2017-09-27 00:00:00
99439           2018-02-15 00:00:00
99440           2018-04-03 00:00:00

[99441 rows x 8 columns]>
Data types:
 order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object
Missing values:
 order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
Duplicate rows: 0
Categorical columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
Numeric columns: []
Date columns: ['order_purchase_timestamp', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
--------------------------------------------------

--- Order Items ---
Shape: (112650, 7)
Columns: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']
cols: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']
head: <bound method NDFrame.head of                                 order_id  order_item_id  \
0       00010242fe8c5a6d1ba2dd792cb16214              1
1       00018f77f2f0320c557190d7a144bdd3              1
2       000229ec398224ef6ca0657da4fc703e              1
3       00024acbcdf0a6daa1e931b038114c75              1
4       00042b26cf59d7ce69dfabb4e55b4fd9              1
...                                  ...            ...
112645  fffc94f6ce00a00581880bf54a75a037              1
112646  fffcd46ef2263f404302a634eb57f7eb              1
112647  fffce4705a9662cd70adb13d4a31832d              1
112648  fffe18544ffabc95dfada21779c9644f              1
112649  fffe41c64501cc87c801fd61db3f6244              1

                              product_id                         seller_id  \
0       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1       e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2       c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3       7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4       ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87
...                                  ...                               ...
112645  4aa6014eceb682077f9dc4bffebc05b0  b8bc237ba3788b23da09c0f1f3a3288c
112646  32e07fd915822b0765e448c4dd74c828  f3c38ab652836d21de61fb8314b69182
112647  72a30483855e2eafc67aee5dc2560482  c3cfdc648177fdbbbb35635a37472c53
112648  9c422a519119dcad7575db5af1ba540e  2b3e4a2a3ea8e01938cabda2a3e5cc79
112649  350688d9dc1e75ff97be326363655e01  f7ccf836d21b2fb1de37564105216cc1

        shipping_limit_date   price  freight_value
0       2017-09-19 09:45:35   58.90          13.29
1       2017-05-03 11:05:13  239.90          19.93
2       2018-01-18 14:48:30  199.00          17.87
3       2018-08-15 10:10:18   12.99          12.79
4       2017-02-13 13:57:51  199.90          18.14
...                     ...     ...            ...
112645  2018-05-02 04:11:01  299.99          43.41
112646  2018-07-20 04:31:48  350.00          36.53
112647  2017-10-30 17:14:25   99.90          16.95
112648  2017-08-21 00:04:32   55.99           8.72
112649  2018-06-12 17:10:13   43.00          12.79

[112650 rows x 7 columns]>
Data types:
 order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object
Missing values:
 order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
Duplicate rows: 0
Categorical columns: ['order_id', 'product_id', 'seller_id', 'shipping_limit_date']
Numeric columns: ['order_item_id', 'price', 'freight_value']
Date columns: ['shipping_limit_date']
--------------------------------------------------

--- Products ---
Shape: (32951, 9)
Columns: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
cols: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
head: <bound method NDFrame.head of                              product_id              product_category_name  \
0      1e9e8ef04dbcff4541ed26657ea517e5                         perfumaria
1      3aa071139cb16b67ca9e5dea641aaa2f                              artes
2      96bd76ec8810374ed1b65e291975717f                      esporte_lazer
3      cef67bcfe19066a932b7673e239eb23d                              bebes
4      9dc1a7de274444849c219cff195d0b71              utilidades_domesticas
...                                 ...                                ...
32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
32950  106392145fca363410d287a815be6de4                    cama_mesa_banho

       product_name_lenght  product_description_lenght  product_photos_qty  \
0                     40.0                       287.0                 1.0
1                     44.0                       276.0                 1.0
2                     46.0                       250.0                 1.0
3                     27.0                       261.0                 1.0
4                     37.0                       402.0                 4.0
...                    ...                         ...                 ...
32946                 45.0                        67.0                 2.0
32947                 41.0                       971.0                 1.0
32948                 50.0                       799.0                 1.0
32949                 60.0                       156.0                 2.0
32950                 58.0                       309.0                 1.0

       product_weight_g  product_length_cm  product_height_cm  \
0                 225.0               16.0               10.0
1                1000.0               30.0               18.0
2                 154.0               18.0                9.0
3                 371.0               26.0                4.0
4                 625.0               20.0               17.0
...                 ...                ...                ...
32946           12300.0               40.0               40.0
32947            1700.0               16.0               19.0
32948            1400.0               27.0                7.0
32949             700.0               31.0               13.0
32950            2083.0               12.0                2.0

       product_width_cm
0                  14.0
1                  20.0
2                  15.0
3                  26.0
4                  13.0
...                 ...
32946              40.0
32947              16.0
32948              27.0
32949              20.0
32950               7.0

[32951 rows x 9 columns]>
Data types:
 product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object
Missing values:
 product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
Duplicate rows: 0
Categorical columns: ['product_id', 'product_category_name']
Numeric columns: ['product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
Date columns: []
--------------------------------------------------

In [5]:
#customers_df_inspect

print(df_customers.shape)

print(df_customers.dtypes)

df_customers['customer_city'].str.strip()
df_customers['customer_city'].unique()
df_orders.head
df_orders['customer_id'].sample(5)
df_customers['customer_zip_code_prefix']

(99441, 5)
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

0        14409
1         9790
2         1151
3         8775
4        13056
         ...
99436     3937
99437     6764
99438    60115
99439    92120
99440     6703
Name: customer_zip_code_prefix, Length: 99441, dtype: int64

In [6]:
#orders_df_inspect
print(df_orders.dtypes)
orders_cols_dtypes = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date']
df_orders[orders_cols_dtypes] = df_orders[orders_cols_dtypes].apply(lambda col:pd.to_datetime(col, errors='coerce'))
df_orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [7]:
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [8]:
df_orders.isnull().sum()
df_orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [9]:
df_order_items.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [10]:
df_order_items.duplicated().sum()

np.int64(0)

In [11]:
df_products.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [12]:
df_products['product_category_name'].unique()

array(['perfumaria', 'artes', 'esporte_lazer', 'bebes',
       'utilidades_domesticas', 'instrumentos_musicais', 'cool_stuff',
       'moveis_decoracao', 'eletrodomesticos', 'brinquedos',
       'cama_mesa_banho', 'construcao_ferramentas_seguranca',
       'informatica_acessorios', 'beleza_saude', 'malas_acessorios',
       'ferramentas_jardim', 'moveis_escritorio', 'automotivo',
       'eletronicos', 'fashion_calcados', 'telefonia', 'papelaria',
       'fashion_bolsas_e_acessorios', 'pcs', 'casa_construcao',
       'relogios_presentes', 'construcao_ferramentas_construcao',
       'pet_shop', 'eletroportateis', 'agro_industria_e_comercio', nan,
       'moveis_sala', 'sinalizacao_e_seguranca', 'climatizacao',
       'consoles_games', 'livros_interesse_geral',
       'construcao_ferramentas_ferramentas',
       'fashion_underwear_e_moda_praia', 'fashion_roupa_masculina',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'industria_comercio_e_negocios', 'telefonia_fixa',
       'construcao_ferramentas_iluminacao', 'livros_tecnicos',
       'eletrodomesticos_2', 'artigos_de_festas', 'bebidas',
       'market_place', 'la_cuisine', 'construcao_ferramentas_jardim',
       'fashion_roupa_feminina', 'casa_conforto', 'audio',
       'alimentos_bebidas', 'musica', 'alimentos',
       'tablets_impressao_imagem', 'livros_importados',
       'portateis_casa_forno_e_cafe', 'fashion_esporte',
       'artigos_de_natal', 'fashion_roupa_infanto_juvenil',
       'dvds_blu_ray', 'artes_e_artesanato', 'pc_gamer', 'moveis_quarto',
       'cine_foto', 'fraldas_higiene', 'flores', 'casa_conforto_2',
       'portateis_cozinha_e_preparadores_de_alimentos',
       'seguros_e_servicos', 'moveis_colchao_e_estofado',
       'cds_dvds_musicais'], dtype=object)

In [13]:
df_order_items.duplicated(subset=["order_id","product_id"]).sum()

np.int64(10225)

In [14]:
df_customers.duplicated(subset="customer_id").sum()

np.int64(0)

In [15]:
df_customers.duplicated(subset="customer_id").sum()

np.int64(0)

In [16]:
df_products.duplicated(subset="product_id").sum()

np.int64(0)

In [17]:
#customers_df_inspect

print(df_customers.head)

print(df_customers.dtypes)

df_customers['customer_city'].sample(3)
df_customers.head()

<bound method NDFrame.head of                             customer_id                customer_unique_id  \
0      06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1      18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2      4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3      b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4      4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066
...                                 ...                               ...
99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

       customer_zip_code_prefix          customer_city customer_state
0                         14409                 franca             SP
1                          9790  sao bernardo do campo             SP
2                          1151              sao paulo             SP
3                          8775        mogi das cruzes             SP
4                         13056               campinas             SP
...                         ...                    ...            ...
99436                      3937              sao paulo             SP
99437                      6764        taboao da serra             SP
99438                     60115              fortaleza             CE
99439                     92120                 canoas             RS
99440                      6703                  cotia             SP

[99441 rows x 5 columns]>
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [18]:
def inspect_df(df, name, deep=False):
    """
    Inspect a DataFrame in a manageable way.
    
    Parameters:
    - df: DataFrame to inspect
    - name: Name of the DataFrame
    - deep: If True, shows full details; if False, shows essentials only
    """
    print(f"\n--- {name} ---")
    
    # Essentials
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    print("Missing values (first 10 columns):\n", df.isnull().sum().head(10))
    
    if deep:
        # More detailed inspection
        print("Data types:\n", df.dtypes)
        print("Duplicate rows:", df.duplicated().sum())
        
        categorical_cols = df.select_dtypes(include='object').columns.tolist()
        numeric_cols = df.select_dtypes(include='number').columns.tolist()
        date_cols = [col for col in df.columns if 'date' in col or 'timestamp' in col]
        head_data = df.head(5)

        print("Categorical columns:", categorical_cols)
        print("Numeric columns:", numeric_cols)
        print("Date columns:", date_cols)
        print("Head data:", head_data)

    
    print("-" * 50)

# Example usage
inspect_df(df_customers, "Customers")          # Essentials only
inspect_df(df_orders, "Orders", deep=True)     # Full inspection

--- Customers ---
Shape: (99441, 5)
Columns: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']
Missing values (first 10 columns):
 customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
--------------------------------------------------

--- Orders ---
Shape: (99441, 8)
Columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
Missing values (first 10 columns):
 order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
Data types:
 order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object
Duplicate rows: 0
Categorical columns: ['order_id', 'customer_id', 'order_status']
Numeric columns: []
Date columns: ['order_purchase_timestamp', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
Head data:                            order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp   order_approved_at  \
0    delivered      2017-10-02 10:56:33 2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37 2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49 2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06 2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39 2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0                    2017-10-18
1                    2018-08-13
2                    2018-09-04
3                    2017-12-15
4                    2018-02-26
--------------------------------------------------

In [19]:
df_customers.head(10)
df_customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [20]:
cols = [col for col in df_customers.select_dtypes(object).columns if 'id' not in col.lower()]
cols = [c.upper() for c in cols]

In [21]:
df_customers[cols].apply(lambda x: x.str.strip().str.upper())

KeyError: "None of [Index(['CUSTOMER_CITY', 'CUSTOMER_STATE'], dtype='object')] are in the [columns]"

In [ ]:
cols = [col.upper() for col in cols]
df_customers[cols].apply(lambda x: x.str.strip().str.upper())

KeyError: "None of [Index(['CUSTOMER_CITY', 'CUSTOMER_STATE'], dtype='object')] are in the [columns]"

In [ ]:
df_customers.columns.tolist()

['customer_id',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state']

In [ ]:
cols

['CUSTOMER_CITY', 'CUSTOMER_STATE']

In [ ]:
# 1) Select object columns that don't contain 'id'
cols_fmt = [col for col in df_customers.select_dtypes(object).columns 
            if 'id' not in col.lower()]

# 2) Format the values
df_customers[cols_fmt] = df_customers[cols_fmt].apply(
    lambda x: x.str.strip().str.upper()
)

# 3) Format column names (IF YOU WANT TO
df_customers.columns = df_customers.columns.str.upper()

In [ ]:
df_orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [ ]:
import os

# Tell PySpark exactly which Python to use
os.environ["PYSPARK_PYTHON"] = r"C:\Python311\python.exe"
os.environ["PYSPARK_DRIVER_PYTHON"] = r"C:\Python311\python.exe"

In [ ]:
import os
from pyspark.sql import SparkSession

# Set Python explicitly for PySpark
os.environ["PYSPARK_PYTHON"] = r"C:\Python311\python.exe"
os.environ["PYSPARK_DRIVER_PYTHON"] = r"C:\Python311\python.exe"

# Start SparkSession safely
spark = (
    SparkSession.builder
    .appName("Day3Test")
    .master("local[1]")  # use 1 core for faster startup
    .getOrCreate()
)

spark.sparkContext.setLogLevel("ERROR")  # reduce logs
print(spark)

# Test DataFrame
df = spark.createDataFrame([(1, "a"), (2, "b")], ["id", "val"])
df.show()

KeyboardInterrupt:

In [ ]:
from pyspark.sql import SparkSession
import os

# Explicitly set Python
os.environ["PYSPARK_PYTHON"] = r"C:\Python311\python.exe"
os.environ["PYSPARK_DRIVER_PYTHON"] = r"C:\Python311\python.exe"

# Start SparkSession with 1 core and minimal memory
spark = (
    SparkSession.builder
    .appName("FastTest")
    .master("local[1]")      # 1 core
    .config("spark.driver.memory", "1g")
    .config("spark.executor.memory", "1g")
    .getOrCreate()
)

spark.sparkContext.setLogLevel("ERROR")
print(spark)

KeyboardInterrupt:

In [23]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB